"""Build config/universe.yaml from the S&P 100 and DAX constituent tables on Wikipedia.

Run monthly on the Mac, review the diff, commit:  uv run python scripts/build_universe.py
"""

import io
import sys
from datetime import date
from pathlib import Path

import httpx
import pandas as pd
import typer
import yaml
import yfinance as yf

from trading_agent.data.universe import Universe
from trading_agent.domain.market import Instrument

SP100_URL = "https://en.wikipedia.org/wiki/S%26P_100"
DAX_URL = "https://en.wikipedia.org/wiki/DAX"
USER_AGENT = "trading-agent/0.1 (personal research; universe refresh)"
OUT = Path(__file__).resolve().parents[1] / "config" / "universe.yaml"

BENCHMARKS = [
    Instrument(
        symbol="SPY",
        yahoo_symbol="SPY",
        name="SPDR S&P 500 ETF Trust",
        market="US",
        exchange="SMART",
        currency="USD",
        kind="etf",
    ),
    Instrument(
        symbol="EXS1",
        yahoo_symbol="EXS1.DE",
        name="iShares Core DAX UCITS ETF (DE)",
        market="EU",
        exchange="IBIS",
        currency="EUR",
        kind="etf",
    ),
]


def _table(url: str, required: set[str]) -> list[dict[str, str]]:
    html = httpx.get(url, headers={"User-Agent": USER_AGENT}, follow_redirects=True, timeout=30)
    html.raise_for_status()
    for table in pd.read_html(io.StringIO(html.text)):
        if required <= set(map(str, table.columns)):
            return [{str(k): str(v) for k, v in r.items()} for r in table.to_dict("records")]
    raise SystemExit(f"no table with columns {required} at {url}")


def sp100() -> list[Instrument]:
    return [
        Instrument(
            symbol=row["Symbol"],
            yahoo_symbol=row["Symbol"].replace(".", "-"),
            name=row["Name"],
            market="US",
            exchange="SMART",
            currency="USD",
            kind="stock",
            sector=row["Sector"],
            indices=("SP100",),
        )
        for row in _table(SP100_URL, {"Symbol", "Name", "Sector"})
    ]


def dax40() -> list[Instrument]:
    instruments: list[Instrument] = []
    for row in _table(DAX_URL, {"Ticker", "Company", "Prime Standard Sector"}):
        base = row["Ticker"].split(".")[0]  # Airbus is listed as AIR.PA; we trade it on Xetra
        instruments.append(
            Instrument(
                symbol=base,
                yahoo_symbol=f"{base}.DE",
                name=row["Company"],
                market="EU",
                exchange="IBIS",
                currency="EUR",
                kind="stock",
                sector=row["Prime Standard Sector"],
                indices=("DAX",),
            )
        )
    return instruments


def unavailable(instruments: list[Instrument]) -> list[str]:
    return [
        i.yahoo_symbol
        for i in instruments
        if yf.Ticker(i.yahoo_symbol).history(period="5d", auto_adjust=False).empty
    ]


def render(universe: Universe) -> str:
    lines = [
        f"# Generated by scripts/build_universe.py on {universe.generated}. Do not edit by hand.",
        f"# Sources: {SP100_URL}, {DAX_URL}",
        f"generated: {universe.generated}",
        "benchmarks: " + yaml.safe_dump(universe.benchmarks, default_flow_style=True).strip(),
        "instruments:",
    ]
    for i in universe.instruments:
        item = i.model_dump(mode="json", exclude={"id", "conid"}, exclude_none=True)
        flow = yaml.safe_dump(item, default_flow_style=True, sort_keys=False, width=10_000)
        lines.append(f"  - {flow.strip()}")
    return "\n".join(lines) + "\n"


def main(verify: bool = typer.Option(True, help="Check every symbol returns Yahoo data.")) -> None:
    us, eu = sp100(), dax40()
    if len(us) < 100 or len(eu) != 40:
        raise SystemExit(f"unexpected constituent counts: S&P 100={len(us)}, DAX={len(eu)}")
    universe = Universe(
        generated=date.today(),  # noqa: DTZ011 - a label for humans
        benchmarks={"US": "SPY", "EU": "EXS1.DE"},
        instruments=[*us, *eu, *BENCHMARKS],
    )
    if verify and (missing := unavailable(universe.instruments)):
        raise SystemExit(f"no Yahoo data for: {', '.join(missing)}")
    OUT.write_text(render(universe), encoding="utf-8")
    print(
        f"wrote {OUT} ({len(us)} US, {len(eu)} EU, {len(BENCHMARKS)} benchmarks)", file=sys.stderr
    )


if __name__ == "__main__":
    typer.run(main)
